--liquibase formatted sql

--changeset anthony-o:1

CREATE TABLE EVENT (
  ID                           BIGINT AUTO_INCREMENT PRIMARY KEY,

  NAME                         VARCHAR(256) NOT NULL,
  KEY                          BINARY(33)   NOT NULL,

  IS_OPENED                    BOOLEAN      NOT NULL DEFAULT FALSE,
  IS_CIRCLE_GIFT_LAUNCHED_ONCE BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE INDEX EVENT_KEY
ON EVENT (KEY);

CREATE TABLE PERSON (
  ID            BIGINT AUTO_INCREMENT PRIMARY KEY,

  NAME          VARCHAR(512) NOT NULL,
  EMAIL         VARCHAR(254), -- email max length thanks to http://stackoverflow.com/a/574698/535203

  LOGIN         VARCHAR(256),
  PASSWORD_HASH BINARY(66),
  SALT          BINARY(66),

  UNIQUE (LOGIN)
);

CREATE INDEX PERSON_LOGIN
ON PERSON (LOGIN);

CREATE TABLE SESSION (
  ID        BIGINT AUTO_INCREMENT PRIMARY KEY,

  PERSON_ID BIGINT     NOT NULL,
  TOKEN     BINARY(66) NOT NULL,

  LAST_USE  DATETIME   NOT NULL,

  UNIQUE (PERSON_ID, TOKEN)
);

CREATE INDEX SESSION_TOKEN
ON SESSION (TOKEN);

CREATE TABLE WISH_LIST (
  ID                                    BIGINT AUTO_INCREMENT PRIMARY KEY,

  PERSON_ID                             BIGINT  NOT NULL,
  EVENT_ID                              BIGINT  NOT NULL,

  IS_PERSON_EVENT_ADMIN                 BOOLEAN NOT NULL DEFAULT FALSE,
  IS_PERSON_PARTICIPATES_IN_CIRCLE_GIFT BOOLEAN NOT NULL DEFAULT FALSE,

  CIRCLE_GIFT_TARGET_PERSON_ID          BIGINT,
  IS_CIRCLE_GIFT_TARGET_PERSON_ID_READ  BOOLEAN NOT NULL DEFAULT FALSE,

  FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID),
  FOREIGN KEY (EVENT_ID) REFERENCES EVENT (ID),
  FOREIGN KEY (CIRCLE_GIFT_TARGET_PERSON_ID) REFERENCES PERSON (ID),

  UNIQUE (PERSON_ID, EVENT_ID)
);

CREATE INDEX WISH_LIST_PERSON_ID_AND_EVENT_ID
ON WISH_LIST (PERSON_ID, EVENT_ID);

CREATE TABLE WISH_ITEM (
  ID                   BIGINT AUTO_INCREMENT PRIMARY KEY,

  NAME                 VARCHAR(1024),
  URL                  VARCHAR(1024),

  WISH_LIST_ID         BIGINT,
  PERSON_ID            BIGINT,

  CREATED_BY_PERSON_ID BIGINT,

  FOREIGN KEY (WISH_LIST_ID) REFERENCES WISH_LIST (ID),
  FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID),
  FOREIGN KEY (CREATED_BY_PERSON_ID) REFERENCES PERSON (ID),

  CHECK (WISH_LIST_ID IS NULL OR PERSON_ID IS NULL) AND NOT (WISH_LIST_ID IS NULL AND PERSON_ID IS NULL),
  CHECK (CREATED_BY_PERSON_ID IS NOT NULL OR PERSON_ID IS NOT NULL)
);

CREATE TABLE RESERVATION (
  ID           BIGINT AUTO_INCREMENT PRIMARY KEY,

  PERSON_ID    BIGINT NOT NULL,
  WISH_ITEM_ID BIGINT NOT NULL,

  FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID),
  FOREIGN KEY (WISH_ITEM_ID) REFERENCES WISH_ITEM (ID),

  UNIQUE (PERSON_ID, WISH_ITEM_ID)
)